services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317" #otlp grpc ( apps -> collector )
      - "4318:4318" #otlp http
      - "8889:8889" #collector prometheus scrape endpoint 
    networks:
      - observability
    restart: 
      unless-stopped
  
  promtail:
    image: grafana/promtail:3.5.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - observability
    restart:
      unless-stopped
  
  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - observability
    restart: unless-stopped
  
  jaeger:
    image: jaegertracing/all-in-one:1.73.0
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686" #UI
      - "14250:14250" # GRPC collector
      - "9411:9411" # zipkin endpoint
    networks:
      - observability
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - observability
    restart: 
      unless-stopped
  
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - observability
    restart: unless-stopped
    
    
volumes:
  grafana-storage:

networks:
  observability:
    external: true
    name: monitoring_observability