receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  fluentforward:
    endpoint: "0.0.0.0:24224"

processors:
  batch:
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 200

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]